apiVersion: core.openfunction.io/v1beta2
kind: Function
metadata:
  name: function-kaniko
  namespace: default
spec:
  build:
    builder: openfunction/kaniko-executor:v1.7.0
    shipwright:
      strategy:
        kind: ClusterBuildStrategy
        name: kaniko
    srcRepo:
      revision: main
      sourceSubPath: apps/buildah/go
      url: https://github.com/OpenFunction/samples.git
  image: openfunctiondev/sample-kankio-go:latest
  imageCredentials:
    name: push-secret
  serving:
    template:
      containers:
        - imagePullPolicy: Always
          name: function
          resources: {}
    triggers:
      http:
        port: 8080
  version: v1.0.0
  workloadRuntime: OCIContainer
