apiVersion: core.openfunction.io/v1beta2
kind: Function
metadata:
  name: sample-node-async-bindings
  namespace: default
spec:
  image: your-docker-registry/image:v1
  serving:
    annotations:
      dapr.io/app-protocol: http
      dapr.io/log-as-json: "false"
      dapr.io/log-level: debug
    bindings:
      mqtt-in:
        metadata:
          - name: consumerID
            value: '{uuid}'
          - name: url
            value: tcp://admin:public@emqx:1883
          - name: topic
            value: in
        type: bindings.mqtt
        version: v1
      mqtt-out:
        metadata:
          - name: consumerID
            value: '{uuid}'
          - name: url
            value: tcp://admin:public@emqx:1883
          - name: topic
            value: out
        type: bindings.mqtt
        version: v1
    outputs:
      - dapr:
          name: mqtt-out
          operation: create
          type: bindings.mqtt
    params:
      DEBUG: common:*,ofn:*
      FUNCTION_TARGET: tryAsync
    template:
      containers:
        - imagePullPolicy: IfNotPresent
          name: function
    triggers:
      dapr:
        - name: mqtt-in
          type: bindings.mqtt
  version: v2.0.0
  workloadRuntime: OCIContainer

