apiVersion: core.openfunction.io/v1beta2
kind: Function
metadata:
  name: sample-node-knative
spec:
  version: v2.0.0
  image: your-docker-registry/image:v1
  # imageCredentials:
  #   name: your-docker-registry-secret
  # build:
  #   builder: openfunction/builder-node:v2-16.13
  #   env:
  #     FUNC_NAME: tryKnative
  #   srcRepo:
  #     url: https://github.com/OpenFunction/samples.git
  #     sourceSubPath: functions/async/mqtt-io-node
  #     revision: main
  serving:
    scaleOptions:
      minReplicas: 0
      maxReplicas: 2
    template:
      containers:
        - name: function # DO NOT change this
          imagePullPolicy: IfNotPresent
    triggers:
      http:
        port: 8080
    params:
      # default to "production"
      NODE_ENV: dev
      # Node.js debug wildcards
      DEBUG: common:*,ofn:*
