apiVersion: core.openfunction.io/v1beta2
kind: Function
metadata:
  name: cron-input
  namespace: default
spec:
  build:
    builder: openfunction/builder-go:latest
    env:
      FUNC_CLEAR_SOURCE: "true"
      FUNC_NAME: HandleCronInput
    #      # Use FUNC_GOPROXY to set the goproxy if failed to fetch go modules
    #      FUNC_GOPROXY: "https://goproxy.cn"
    srcRepo:
      revision: main
      sourceSubPath: functions/async/bindings/cron-input
      url: https://github.com/OpenFunction/samples.git
  image: openfunctiondev/cron-input:v1
  imageCredentials:
    name: push-secret
  serving:
    bindings:
      cron:
        metadata:
          - name: schedule
            value: '@every 2s'
        type: bindings.cron
        version: v1
    template:
      containers:
        - imagePullPolicy: IfNotPresent
          name: function
          resources: { }
    triggers:
      dapr:
        - name: cron
          type: bindings.cron
  version: v2.0.0
  workloadRuntime: OCIContainer
